### ISSUE TITLE
Doesn't work with an array of inputs.

### ISSUE THREAD

**Issue by RebeccaStevens** [bengsfort/rollup-plugin-copy-assets#4]
This line assumes the input is string:

https://github.com/bengsfort/rollup-plugin-copy-assets/blob/85dbeb0a201b8c4e6853205a56bc75e4d8a9527e/src/index.js#L18

**Comment by bengsfort** [comment]
Good spot! Going to fix this today. I'm going to just make it output to the same directory it would with a singular input, or copy the files to multiple directories if the input base directories are different, since it tries to maintain directory relativity to the input base directory. 

As I haven't been doing web app dev for a few months and therefore haven't been using Rollup, please let me know if there is a more desirable functionality.

**Comment by bengsfort** [comment]
Defaulted to using the base path of the first item in the input array, fixed in v2.0.0.
